version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Docker" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
