name: Python package

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest ./porkbun_ddns/test
      - name: Lint with ruff
        env: 
          PY_VER: ${{ matrix.python-version }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          PY_VER=$(echo py${PY_VER} | tr -d '.')
          ruff --format=github --select=E9,F63,F7,F82 --ignore=E501 --target-version=${PY_VER} .
